version: "3.3"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "moviemang"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PORT: "3306"
      MYSQL_HOST: "db"
      MYSQL_PORT: "3306"
    logging:
      driver: "json-file"
      options:
        max-size: "8m"
        max-file: "10"
  app:
    build: .
    ports:
      - "8000:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "8m"
        max-file: "10"
