#!groovy
@Library('dockerBuild') _
pipeline {
    agent any

    environment{
        GIT_COMMIT_HASH = sh (script: "git log -n 1 --pretty=format:'%H'", returnStdout: true)
        GIT_PRE_COMMIT_HASH = sh (script: "git show HEAD@{1} -1 --pretty=format:'%H'", returnStdout: true)
        GIT_PRE_COMMIT_TAG = "${GIT_PRE_COMMIT_HASH.substring(0,8)}"
        GIT_COMMIT_TAG = "${GIT_COMMIT_HASH.substring(0,8)}"
        SYSTEM_NAME = sh (returnStdout: true,
        script: """
            basename \$(git remote get-url origin) | sed -e "s/.git\$//"
        """)
    }
    
    stages {
        stage('Docker Build') {
        steps {
            sh 'Docker Image Build Start'
            dockerBuild("${GIT_COMMIT_TAG}", "${GIT_PRE_COMMIT_TAG}","${SYSTEM_NAME}")
            sh '''
            echo "Building Docker Image"
            pwd
            '''
            }
        }
        stage('Docker RUN') {
            steps {
                sh '''
                echo "Docker RUN"
                docker rm -f mmback
                docker run -d -p 8000:8000 --name mmback ${GIT_COMMIT_TAG}
                '''
            }
        }
    }
}