pipeline {
    agent any

    environment{
        GIT_COMMIT_HASH = sh (script: "git log -n 1 --pretty=format:'%H'", returnStdout: true)
    }
    
    

    
    stages {
        stage('Build') {
        steps {
            sh "echo Git commit hash: ${GIT_COMMIT_HASH}"
            sh 'echo "Hello World"'
        }
        }
    }
}